name: Send email

on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: read-all

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Last Update
        uses: actions/cache@v4
        with:
          path: dist/lastupdate
          key: ${{ runner.os }}-lastupdate

      # - name: Last successful run
      #   id: last_success
      #   run: |
      #     echo "LAST_SUCCESS=$(gh api -XGET repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/send-email.yaml/runs --jq '.workflow_runs[0].run_started_at' -F status=success -F per_page=1)" >> $GITHUB_OUTPUT
      #     echo "LAST_SUCCESS=$(gh api -XGET repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/send-email.yaml/runs --jq '.workflow_runs[0].run_started_at' -F status=success -F per_page=1)" >> $GITHUB_STEP_SUMMARY

      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci

      - name: Create email
        run: |
          npm run email actionUrl=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} lastSuccess=${{ steps.last_success.outputs.LAST_SUCCESS }}

      - name: Check email exists
        id: check_email
        run: |
          echo "Last update on "
          cat dist/lastupdate >> $GITHUB_STEP_SUMMARY
          if [ -f dist/email.html ]; then
            echo "files_exists=true" >> $GITHUB_OUTPUT
            echo "### New update email :inbox_tray:" >> $GITHUB_STEP_SUMMARY
          else
            echo "### No updates since last run :zzz:" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Send email
        if: steps.check_email.outputs.files_exists == 'true'
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_PORT }}
          secure: true

          username: ${{ vars.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}

          subject: RSS to Email
          to: ${{ vars.MAIL_TO }}
          from: ${{ vars.FROM }}

          html_body: file://dist/email.html
